Name - Maahi Sadrani
PRN - 25070123069

In [ ]:
# Experiment No. 13:
# Aim:To perform processing on a dataset and dealing with missing values

In [3]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],
                    'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [4]:
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [5]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [6]:
df1.isna().sum() # Columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [7]:
df1.isna().sum(axis=1)  #Rowwise na values

0    0
1    1
2    2
dtype: int64

In [8]:
df1.dropna() # NaN Rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [9]:
df1.dropna(axis=1)

   C3
0  10
1  20
2  30

In [10]:
df1.fillna(0)

     C1    C2  C3
0  11.0  15.0  10
1  21.0   0.0  20
2   0.0   0.0  30

In [11]:
df1.fillna(df1.mean()) # Mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [12]:
df1.fillna(df1.mean(axis=1))

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [13]:
# Preprocessing on a dataset
data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)
print(df)

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC       10/06/23

In [15]:
# Step 2: Replace '-' with Nan tp marks missing value

df.replace("-",np.nan,inplace=True)
df

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [16]:
# Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC       10/06/23

In [18]:
# Step 3: Checking thne missing values
print("\nMissing Values:")
print(df.isna().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [23]:
# Step 4: Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Marks"].fillna(df["Marks"].median(),inplace=True)
df

/tmp/ipykernel_14775/708562851.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)
/tmp/ipykernel_14775/708562851.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        cse     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [24]:
# Step 5: Fix inconsistent text for text formating
df["Department"]=df["Department"].str.upper()
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        CSE     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [29]:
# Step 6: Convert admission date to standard datetime format

df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],errors='coerece'
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-01-06
1      102  Rohan  20.75   90.0         IT     2023-03-06
2      103  Meera  21.00   86.5        CSE     2023-05-06
3      104  Karan  20.00   88.0        CSE     2023-07-06
4      105   Anil  22.00   76.0       E&TC            NaT